name: Build and deploy the develop version to firebase distribution.

on:
  push:
    branches:
      - main

jobs:
  build_deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Set up Ruby 3.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permission to Execute
        run: chmod +x gradlew

      - name: Install bundle
        run: |
          gem install bundler -v 2.4.22
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install plugins
        run: bundle exec fastlane add_plugin run_tests_firebase_testlab

      - name: Configure the keystore to build the DEV app.
        env:
          ANDROID_KEYSTORE_FILE_B64: ${{ secrets.ANDROID_KEYSTORE_FILE_B64 }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        run: |
          echo "$ANDROID_KEYSTORE_FILE_B64" | base64 -d > keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties

      - name: Configure google-service-json files for the DEV app
        env:
          DEV_API_KEY_B64: ${{ secrets.DEV_API_KEY_B64 }}
          DEV_GOOGLE_SERVICES_JSON_B64: ${{ secrets.DEV_GOOGLE_SERVICES_JSON_B64 }}
          DEV_FIREBASE_DIST_ACCOUNT_JSON_B64: ${{ secrets.DEV_FIREBASE_DIST_ACCOUNT_JSON_B64 }}
        run: |
          echo "$DEV_API_KEY_B64" | base64 -d >> gradle.properties
          echo "$DEV_GOOGLE_SERVICES_JSON_B64" | base64 -d > app/google-services.json
          echo "$DEV_FIREBASE_DIST_ACCOUNT_JSON_B64" | base64 -d > firebase-distribution-service-account.json
          echo 'package_name("net.eidas2sandkasse.demolommebok.dev")' >> fastlane/Appfile

      - name: Build and deploy the develop version to firebase distribution.
        run: bundle exec fastlane deploy_dev