name: Demo Builds
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Demo-Release-Build"
        default: "Generate demo release build"
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checking out branch
        uses: actions/checkout@v3
  
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
  
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build Demo Release apk
        # env:
          # RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          # RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          # RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        # run: ./gradlew assembleRelease --stacktrace
        run: ./gradlew tasks --stacktrace
