name: CI

on:
  pull_request:
    types: [ opened, reopened ]
  push:

jobs:
  build-gradle:
    name: Build
    # Run on external PRs, but not on internal PRs since those will be run by push to branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle Wrapper
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: wrapper
          arguments: build

  unit-tests:
    runs-on: ubuntu-latest
    needs: [ build-gradle ]
    permissions:
      contents: read
    steps:
      - name: Checkout project source code
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle Wrapper
        uses: gradle/gradle-build-action@v2.9.0
        with:
          arguments: test --full-stacktrace