name: Code Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  code-quality: write

jobs:
  coverage:
    uses: eu-digital-identity-wallet/eudi-infra-ci/.github/workflows/code_coverage_android.yml@feat/kover_coverage_report_implementation
    with:
      kover_task: koverXmlReportDevDebug
      kover_output_path: assembly-logic/build/reports/kover/
